export default async function ImgPage({
  searchParams,
}: {
  searchParams: Promise<{ content?: string; color?: string; bg?: string }>;
}) {
  const params = await searchParams;

  if (!params.content) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center text-slate-400 p-4">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-16 h-16 mb-4 opacity-50"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z"
          />
        </svg>
        <p className="font-medium">Không tìm thấy nội dung QR</p>
      </div>
    );
  }

  const apiUrl = `/api/qr?content=${params.content}&color=${
    params.color ?? "#000000"
  }&bg=${params.bg ?? "#ffffff"}`;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-100 to-slate-200 flex items-center justify-center p-6">
      <div className="bg-white rounded-3xl shadow-xl border border-white/50 p-10 max-w-sm w-full text-center transition-all hover:shadow-2xl">
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-slate-800 tracking-tight">
            QR Code Preview
          </h2>
          <p className="text-slate-500 text-sm mt-1">
            Quét mã bên dưới để truy cập
          </p>
        </div>

        <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100 inline-block shadow-inner">
          <img
            src={apiUrl}
            alt="QR Code"
            className="w-64 h-64 object-contain mix-blend-multiply"
          />
        </div>

        <div className="mt-8 pt-6 border-t border-slate-100">
          <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">
            Generated by PAD
          </p>
        </div>
      </div>
    </div>
  );
}
