// export default async function ImgPage({
//   searchParams,
// }: {
//   searchParams: Promise<{ content?: string; color?: string; bg?: string }>;
// }) {
//   const params = await searchParams;

//   if (!params.content) {
//     return (
//       <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center text-slate-400 p-4">
//         <svg
//           xmlns="http://www.w3.org/2000/svg"
//           fill="none"
//           viewBox="0 0 24 24"
//           strokeWidth={1.5}
//           stroke="currentColor"
//           className="w-16 h-16 mb-4 opacity-50"
//         >
//           <path
//             strokeLinecap="round"
//             strokeLinejoin="round"
//             d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z"
//           />
//         </svg>
//         <p className="font-medium">Không tìm thấy nội dung QR</p>
//       </div>
//     );
//   }

//   const content = params.content ? decodeURIComponent(params.content) : "";

//   const color = params.color ? decodeURIComponent(params.color) : "#000000";

//   const bg = params.bg ? decodeURIComponent(params.bg) : "#ffffff";

//   const apiUrl = `/api/qr?content=${encodeURIComponent(
//     content
//   )}&color=${encodeURIComponent(color)}&bg=${encodeURIComponent(bg)}`;

//   return (
//     <div className="min-h-screen bg-gradient-to-br from-slate-100 to-slate-200 flex items-center justify-center p-6">
//       <div className="bg-white rounded-3xl shadow-xl border border-white/50 p-10 max-w-sm w-full text-center transition-all hover:shadow-2xl">
//         <div className="mb-6">
//           <h2 className="text-2xl font-bold text-slate-800 tracking-tight">
//             QR Code Preview
//           </h2>
//           <p className="text-slate-500 text-sm mt-1">
//             Quét mã bên dưới để truy cập
//           </p>
//         </div>

//         <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100 inline-block shadow-inner">
//           <img
//             src={apiUrl}
//             alt="QR Code"
//             className="w-64 h-64 object-contain"
//             style={{ imageRendering: "pixelated" }}
//           />
//         </div>

//         <div className="mt-8 pt-6 border-t border-slate-100">
//           <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">
//             Generated by PAD
//           </p>
//         </div>
//       </div>
//     </div>
//   );
// }

// import Link from "next/link";

// export default async function ImgPage({
//   searchParams,
// }: {
//   searchParams: Promise<{ content?: string; color?: string; bg?: string }>;
// }) {
//   const params = await searchParams;

//   const content = params.content ? decodeURIComponent(params.content) : "";
//   const color = params.color ? decodeURIComponent(params.color) : "#000000";
//   const bg = params.bg ? decodeURIComponent(params.bg) : "#ffffff";

//   const apiUrl = `/api/qr?content=${encodeURIComponent(
//     content
//   )}&color=${encodeURIComponent(color)}&bg=${encodeURIComponent(bg)}`;

//   if (!params.content) {
//     return (
//       <div className="min-h-screen flex flex-col items-center justify-center bg-zinc-50 p-6 font-sans">
//         <div className="text-center max-w-md">
//           <div className="w-16 h-16 bg-zinc-200 rounded-full flex items-center justify-center mx-auto mb-4">
//             <span className="text-2xl">?</span>
//           </div>
//           <h2 className="text-lg font-bold text-zinc-900 mb-2">
//             Liên kết không hợp lệ
//           </h2>
//           <p className="text-zinc-500 mb-6 text-sm">
//             Chúng tôi không tìm thấy dữ liệu để tạo mã QR.
//           </p>
//           <Link
//             href="/"
//             className="text-sm font-medium text-zinc-900 underline hover:text-zinc-600"
//           >
//             Quay về trang chủ
//           </Link>
//         </div>
//       </div>
//     );
//   }

//   return (
//     <div className="min-h-screen flex items-center justify-center bg-zinc-100 p-6 font-sans">
//       <div className="bg-white p-8 sm:p-12 rounded-2xl shadow-xl shadow-zinc-200/50 max-w-sm w-full text-center border border-zinc-100">
//         <div className="mb-8">
//           <h2 className="text-xl font-bold text-zinc-900 tracking-tight">
//             QR Code
//           </h2>
//           <p className="text-xs text-zinc-400 mt-1 uppercase tracking-widest">
//             Scan to view
//           </p>
//         </div>

//         <div className="relative inline-block group">
//           {/* Decorative corner markers */}
//           <div className="absolute -top-2 -left-2 w-4 h-4 border-t-2 border-l-2 border-zinc-900"></div>
//           <div className="absolute -top-2 -right-2 w-4 h-4 border-t-2 border-r-2 border-zinc-900"></div>
//           <div className="absolute -bottom-2 -left-2 w-4 h-4 border-b-2 border-l-2 border-zinc-900"></div>
//           <div className="absolute -bottom-2 -right-2 w-4 h-4 border-b-2 border-r-2 border-zinc-900"></div>

//           <img
//             src={apiUrl}
//             alt="QR Code"
//             className="w-64 h-64 object-contain"
//             style={{ imageRendering: "pixelated" }}
//           />
//         </div>

//         <div className="mt-10 pt-6 border-t border-zinc-100">
//           <Link
//             href="/"
//             className="inline-flex items-center justify-center gap-2 text-xs font-semibold text-zinc-400 hover:text-zinc-900 transition-colors"
//           >
//             <span>Powered by PAD</span>
//           </Link>
//         </div>
//       </div>
//     </div>
//   );
// }

import Link from "next/link";

export default async function ImgPage({
  searchParams,
}: {
  searchParams: Promise<{ content?: string; color?: string; bg?: string }>;
}) {
  const params = await searchParams;

  const content = params.content ? decodeURIComponent(params.content) : "";
  const color = params.color ? decodeURIComponent(params.color) : "#000000";
  const bg = params.bg ? decodeURIComponent(params.bg) : "#ffffff";

  const apiUrl = `/api/qr?content=${encodeURIComponent(
    content
  )}&color=${encodeURIComponent(color)}&bg=${encodeURIComponent(bg)}`;

  if (!params.content) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-slate-50 font-sans p-6 text-center">
        <div className="w-20 h-20 bg-slate-200 rounded-3xl flex items-center justify-center mb-6 animate-pulse">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-10 h-10 text-slate-400"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z"
            />
          </svg>
        </div>
        <h1 className="text-2xl font-bold text-slate-800 mb-2">
          Không tìm thấy mã QR
        </h1>
        <p className="text-slate-500 mb-8">
          Liên kết này có thể bị lỗi hoặc thiếu dữ liệu.
        </p>
        <Link
          href="/"
          className="px-8 py-3 bg-slate-900 text-white font-semibold rounded-xl hover:bg-slate-800 transition-all"
        >
          Tạo mã mới
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0F172A] p-6 font-sans relative overflow-hidden">
      {/* Background decoration */}
      <div className="absolute top-0 left-0 w-full h-full opacity-20 pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500 rounded-full mix-blend-screen filter blur-[128px]"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-indigo-500 rounded-full mix-blend-screen filter blur-[128px]"></div>
      </div>

      <div className="relative z-10 w-full max-w-xs sm:max-w-sm">
        <div className="bg-white/90 backdrop-blur-md p-2 rounded-[2rem] shadow-2xl shadow-indigo-500/20 ring-1 ring-white/20">
          <div className="bg-white border border-slate-100 rounded-[1.5rem] p-8 text-center">
            <div className="mb-8">
              <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-slate-100 rounded-full mb-4">
                <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
                <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
                  Ready to scan
                </span>
              </div>
              <h1 className="text-2xl font-black text-slate-900 tracking-tighter">
                QR Code
              </h1>
            </div>

            <div className="relative mx-auto w-fit mb-8 p-4 rounded-2xl bg-white shadow-[0_10px_40px_-10px_rgba(0,0,0,0.1)] ring-1 ring-slate-100">
              <img
                src={apiUrl}
                alt="QR Code"
                className="w-56 h-56 object-contain rounded-lg"
                style={{ imageRendering: "pixelated" }}
              />
              {/* Decor elements */}
              <div className="absolute -top-1 -left-1 w-3 h-3 border-t-2 border-l-2 border-slate-900 rounded-tl-sm"></div>
              <div className="absolute -top-1 -right-1 w-3 h-3 border-t-2 border-r-2 border-slate-900 rounded-tr-sm"></div>
              <div className="absolute -bottom-1 -left-1 w-3 h-3 border-b-2 border-l-2 border-slate-900 rounded-bl-sm"></div>
              <div className="absolute -bottom-1 -right-1 w-3 h-3 border-b-2 border-r-2 border-slate-900 rounded-br-sm"></div>
            </div>

            <div className="pt-6 border-t border-slate-100/80">
              <Link
                href="/"
                className="group inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-indigo-600 transition-colors"
              >
                <span className="group-hover:translate-x-[-2px] transition-transform">
                  ←
                </span>
                Create your own
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
